// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBohKO1P13XB43kICHoaBrYuotZ1xD5Cgc',
    appId: '1:392328178263:web:f939d1149feb4210fad112',
    messagingSenderId: '392328178263',
    projectId: 'rethics-d47fa',
    authDomain: 'rethics-d47fa.firebaseapp.com',
    storageBucket: 'rethics-d47fa.firebasestorage.app',
    measurementId: 'G-0NK9HVZ9P6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBicuSH-74LrT85CnF8EsQtlP6GM28DnS0',
    appId: '1:392328178263:android:524f93408f1e4436fad112',
    messagingSenderId: '392328178263',
    projectId: 'rethics-d47fa',
    storageBucket: 'rethics-d47fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB47HPez4RXccWyg81otXiRAOv-9NRXvqQ',
    appId: '1:392328178263:ios:9093d34a08278833fad112',
    messagingSenderId: '392328178263',
    projectId: 'rethics-d47fa',
    storageBucket: 'rethics-d47fa.firebasestorage.app',
    iosBundleId: 'com.rethicsai.app.rethicsai',
  );
}
